// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATdwQb4aHT9yres5TDLdurC_sBMc7LEqA',
    appId: '1:416666961727:web:5d4affc6efe968ae7bf58a',
    messagingSenderId: '416666961727',
    projectId: 'flutter-chat-app-270aa',
    authDomain: 'flutter-chat-app-270aa.firebaseapp.com',
    storageBucket: 'flutter-chat-app-270aa.appspot.com',
    measurementId: 'G-YBHH7099K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssnXUTd8awOM0cuHhFOlMAX_jvFNLqSA',
    appId: '1:416666961727:android:5a762546c9fa4c647bf58a',
    messagingSenderId: '416666961727',
    projectId: 'flutter-chat-app-270aa',
    storageBucket: 'flutter-chat-app-270aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtddm7UC6mff0KeS_HUEhiMn-PECpJygI',
    appId: '1:416666961727:ios:073f04a7e430b64c7bf58a',
    messagingSenderId: '416666961727',
    projectId: 'flutter-chat-app-270aa',
    storageBucket: 'flutter-chat-app-270aa.appspot.com',
    iosClientId: '416666961727-h0hopapmi1ce3otorc75mmlvgnhag7cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtddm7UC6mff0KeS_HUEhiMn-PECpJygI',
    appId: '1:416666961727:ios:073f04a7e430b64c7bf58a',
    messagingSenderId: '416666961727',
    projectId: 'flutter-chat-app-270aa',
    storageBucket: 'flutter-chat-app-270aa.appspot.com',
    iosClientId: '416666961727-h0hopapmi1ce3otorc75mmlvgnhag7cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
